version: '3'
services:
  postgres:
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=training
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/data
    volumes:
      - ./data:/data
  pgadmin:
    image: dpage/pgadmin4:6.2
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@training.pl
      - PGADMIN_DEFAULT_PASSWORD=admin